-- MySQL Script generated by MySQL Workbench
-- sex 15 jan 2021 19:39:59 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wish_list
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wish_list
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wish_list` ;
USE `wish_list` ;

-- -----------------------------------------------------
-- Table `wish_list`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wish_list`.`USER` (
  `ID` INT NOT NULL COMMENT 'User table identifier',
  `USERNAME` VARCHAR(100) NOT NULL COMMENT 'Username used to log into the app',
  `EMAIL` VARCHAR(45) NULL COMMENT 'User email address',
  `PASSWORD` VARCHAR(45) NOT NULL COMMENT 'User password (must be stored encrypted)',
  `FIRST_NAME` VARCHAR(45) NOT NULL COMMENT 'User first name',
  `LAST_NAME` VARCHAR(45) NOT NULL COMMENT 'User last name',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
COMMENT = 'User associated to the wish list.';


-- -----------------------------------------------------
-- Table `wish_list`.`WISH_LIST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wish_list`.`WISH_LIST` (
  `ID` INT NOT NULL COMMENT 'Wish list identifier',
  `NAME` VARCHAR(100) NOT NULL COMMENT 'Wish list short name',
  `DESCRIPTION` VARCHAR(4000) NULL COMMENT 'Wish list description',
  `PUBLIC` CHAR(1) NOT NULL DEFAULT 'Y' COMMENT 'Indicator that this wishlist is public or private. Allowed values are Y-Yes or N-No.',
  `DATE_CREATED` DATETIME NOT NULL COMMENT 'The Wish list creation date',
  `DATE_MODIFIED` DATETIME NULL COMMENT 'The Wish list change date',
  `USER_ID` INT NOT NULL COMMENT 'The wish list owner ID',
  PRIMARY KEY (`ID`, `USER_ID`),
  INDEX `fk_WISH_LIST_USER_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_WISH_LIST_USER`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `wish_list`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Table used to store users wish lists';


-- -----------------------------------------------------
-- Table `wish_list`.`ITEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wish_list`.`ITEM` (
  `ID` INT NOT NULL COMMENT 'Wish list item ID',
  `NAME` VARCHAR(100) NOT NULL COMMENT 'Wish list item name',
  `URL` VARCHAR(300) NULL COMMENT 'Wish list item URL',
  `DATE_CREATED` DATETIME NOT NULL COMMENT 'Wish list item creation date',
  `PRICE` DECIMAL NULL COMMENT 'Wish list item price',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
COMMENT = 'Wish list items';


-- -----------------------------------------------------
-- Table `wish_list`.`ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wish_list`.`ROLE` (
  `NAME` VARCHAR(20) NOT NULL COMMENT 'Role name',
  PRIMARY KEY (`NAME`))
ENGINE = InnoDB
COMMENT = 'User role';


-- -----------------------------------------------------
-- Table `wish_list`.`USER_ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wish_list`.`USER_ROLE` (
  `USER_ID` INT NOT NULL,
  `ROLE_NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`USER_ID`, `ROLE_NAME`),
  INDEX `fk_USER_has_ROLE_ROLE1_idx` (`ROLE_NAME` ASC) VISIBLE,
  INDEX `fk_USER_has_ROLE_USER1_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_USER_has_ROLE_USER1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `wish_list`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_has_ROLE_ROLE1`
    FOREIGN KEY (`ROLE_NAME`)
    REFERENCES `wish_list`.`ROLE` (`NAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wish_list`.`WISH_LIST_ITEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wish_list`.`WISH_LIST_ITEM` (
  `WISH_LIST_ID` INT NOT NULL COMMENT 'Wish list ID',
  `WISH_LIST_USER_ID` INT NOT NULL COMMENT 'Wish list owner ID',
  `ITEM_ID` INT NOT NULL COMMENT 'Item ID',
  PRIMARY KEY (`WISH_LIST_ID`, `WISH_LIST_USER_ID`, `ITEM_ID`),
  INDEX `fk_WISH_LIST_has_ITEM_ITEM1_idx` (`ITEM_ID` ASC) VISIBLE,
  INDEX `fk_WISH_LIST_has_ITEM_WISH_LIST1_idx` (`WISH_LIST_ID` ASC, `WISH_LIST_USER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_WISH_LIST_has_ITEM_WISH_LIST1`
    FOREIGN KEY (`WISH_LIST_ID` , `WISH_LIST_USER_ID`)
    REFERENCES `wish_list`.`WISH_LIST` (`ID` , `USER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WISH_LIST_has_ITEM_ITEM1`
    FOREIGN KEY (`ITEM_ID`)
    REFERENCES `wish_list`.`ITEM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Joint table of wish list items';


-- -----------------------------------------------------
-- Table `wish_list`.`ITEM_HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wish_list`.`ITEM_HISTORY` (
  `DATE` DATETIME NOT NULL COMMENT 'History date ',
  `PRICE` DECIMAL NOT NULL COMMENT 'History price',
  `ITEM_ID` INT NOT NULL COMMENT 'Item identifier',
  PRIMARY KEY (`ITEM_ID`),
  CONSTRAINT `fk_ITEM_HISTORY_ITEM1`
    FOREIGN KEY (`ITEM_ID`)
    REFERENCES `wish_list`.`ITEM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Item price history';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
